### ISSUE TITLE
Some trainee thumbnail not crop correctly

### ISSUE THREAD

**Issue by joshuaavalon** [umasagashi/umacapture#65]
## Steps to Reproduce
Unknown.
But I use autohotkey script for inputting. So, every capture should be scrolled in the exact same rate.

## Expected Behavior
Trainee thumbnail crop correctly.

## Current Behavior
Trainee thumbnail not crop correctly which make matching some trainee not correct.

### Reproducibility Rate
11 / 50

### Screenshots
![skill](https://user-images.githubusercontent.com/7152420/189515463-1dfa11fa-462a-4c0a-a486-9d759996245f.png)
![image](https://user-images.githubusercontent.com/7152420/189515445-2e512f4c-09a5-4265-bd7e-a96699950735.png)
![image](https://user-images.githubusercontent.com/7152420/189515429-78e1b83a-45fb-405f-8bda-151339ac0dda.png)

## Environment
- App Version: 0.0.3
- OS: Windows 10

**Comment by joshuaavalon** [comment]
![image](https://user-images.githubusercontent.com/7152420/189515651-e52d58f2-82e5-4983-9bd8-19953ffa3583.png)

It seems like `factor.jpg` is not captured correctly but no error is thrown.

**Comment by umasagashi** [comment]
Thanks for reporting the issue!

At this point, I suspect that you may have started scrolling too early. When the app is ready to start scrolling, [this sound](https://github.com/umasagashi/umacapture/blob/develop/assets/sound/attention_weak.wav) will be played. In other words, if you did not hear this sound, then you have started scrolling too early.

However, even if it's too early, such a result should be extremely rare, so there may be other causes. If you heard the sound (or inserted enough delay) and still reproduce same problem, please reopen this issue.
